### ISSUE TITLE
[QUESTION] Is there a small example of USB Host support communicating with CDC device?

### ISSUE THREAD

**Issue by shreeve** [Panda381/PicoLibSDK#5]
The USB Host support looks great!

Is there a short example of how to use this USB Host support to communicate with a CDC device?

**Comment by Panda381** [comment]
See sample PicoPad/USB/USBUART. That sample communicate with console in PC as UART, as host or as device. At first, you need to modify config.h - disable USE_USB_STDIO and enable USE_USB_DEV_CDC and USE_USB_HOST_CDC.

**Comment by shreeve** [comment]
Thank you!
